services:
  nginx:
    image: nginx:1.24-bullseye-perl
    container_name: acatrans
    ports:
      - "3000:80"  # 将宿主机的8080端口映射到容器的80端口
    volumes:
      - .:/usr/share/nginx/html  # 将本地的html目录映射到容器的nginx默认网页目录
